version: '3.4'

services:
  sportsstore:
    image: ${DOCKER_REGISTRY-}sportsstore
    build:
      context: .
      dockerfile: SportsStore/Dockerfile
    depends_on:
            - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
    environment:
       SA_PASSWORD: "123409876ASDfds@!"
       ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

volumes:
  data: